#how quickly we can stand up a new website using EC2 for compute and S3 for content.

--- #deploy to aws with ansible supplemental playbook
- hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ansible/keys.yml
  tasks:
    - name: Get VPC Subnet Facts
      ec2_vpc_subnet_info:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          region: "{{ AWS_REGION }}"
      register: subnet_facts
    
    - name: Add subnet id to env_vars.yml
      lineinfile:
        path: /home/ansible/env_vars.yml
        line: "DEFAULT_VPC_SUBNET: {{ subnet_facts.subnets[0].subnet_id }}"
    
    - name: Get EC2 instance facts
      ec2_metadata_facts:

    - name: Add security group name to env_vars.yml
      lineinfile:
          path: /home/ansible/env_vars.yml
          line: "SEC_GROUP_NAME: {{ ansible_ec2_security_groups }}"

---
- hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ansible/env_vars.yml
  tasks:
    - name: Create AWS key pair using Ansible's key.
      local_action: ec2_key
      args:
        region: "{{ AWS_REGION }}"
        name: ansible_keypair
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Provision instances
      local_action: ec2
      args:
        region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        group: "{{ SEC_GROUP_NAME }}"
        keypair: ansible_keypair
        image: "{{ AMI_ID }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: yes
        instance_tags:
          type: web
        count: 1
      register: ec2

    - name: Add host to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webservers
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
      loop: "{{ ec2.instances }}"

    - name: Create S3 Bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: create
        permission: public-read

    - name: Add file to bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: put
        object: /webimage.png
        src: /home/ansible/webimage.png
        permission: public-read

- hosts: webservers
  gather_facts: no
  vars_files:
    - /home/ansible/env_vars.yml
  remote_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 5
        timeout: 90

    - name: Collect instance facts
      ec2_metadata_facts:

    - name: Install HTTPD
      become: yes
      yum:
        name: httpd
        state: present

    - name: Start HTTPD
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy content
      become: yes
      template:
        src: /home/ansible/index.html.j2
        dest: /var/www/html/index.html
  
#Run the Playbook
#Source our keys.sh file:

#source keys.sh
#Run the following command:

#ansible-playbook /home/ansible/deploy.yml


