#when it comes to automation, you need to be able to get a hold of various bits of information without having to manually provide that information, and we can do that in ansible using facts.
#how to collect facts how we can use facts to do interesting things

- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Get VPC facts
      ec2_vpc_net_facts:
          aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
          ec2_region: "{{ AWS_REGION }}"
      register: vpc_facts
    - debug:
        var: vpc_facts
    