- hosts: localhost
  gather_facts: no 
  vars_files:
    - keys.yml
  tasks:
    - name: Get AMI facts
      ec2_ami_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_secret_ACCESS_KEY }}"
        ec2_region: "{{ AWS_OWNER }}"
        owner: "{{ AWS_OWNER }}"
      register: ami_facts
    - name: Output information
      debug:
        msg: "{{ item.description }}"
      loop_control:
        label: "{{ item.image.id }}"
      loop: "{{ ami_facts.images }}"

#When looping over complex data structures, the console output of your task can be enormous. To limit the displayed output, use the label directive with loop_control.
