- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: remove alarm
      ec2_metric_alarm:
        name: "cpu-low"
        state: absent
        aws_access_key: "{{ AWS_ACCESS KEY ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
    - name: create alarm
      ec2_metric_alarm:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: present
        name: "cpu-high"
        metric: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: Average
        comparision: ">="
        threshold: 90.0
        period: 300
        evaluation_periods: 3
        unit: "Percent"
        dimensions: {"instnaceID": 'i-6870dcsccdscd'}
        