# using vault for secret and access key in aws

#ansible-vault encrypt /home/ansible/secret-file

---
- hosts: localhost
  vars_files:
    - /home/ansible/secret-file

# ansible-playbook --ask-vault-pass playbook.yml

#another exemple:
#we encrypt keys.yml
---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: Change instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags:
          Name: Demo

#AKIAVGJECQLFLHMCTX7T
#LuG/ZragSZhfojKN0bM5p6oJEHX2n0kZoDwduNvW
