# a snapshot is a differential backup of a given volume.
# which is handy for backup puroposes or disaster recovery

- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  tasks:
    - name: Gather snapshot facts
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
    - name: Create Volume snapshot
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-27889900
        device_name: /dev/xvdf
        state: present
        description: "On demand volume backup"