apiVersion: apps/v1
kind: Deployement
metadata:
  labels:
    tier: frontend
    app: my-webapp
  name: my-webapp
spec:
    replicas: 2
    selector:
      matchLabels:
        app: my-webapp
    template:
        metadata:
          app: my-webapp
        sepc:
          containers:
            - image: nginx
              name: nginx
              