apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: slow
    hostPath:
      path: /etc/hostPath
      type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: hostpath-pvc
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Mi
    storageClassName: slow

---
apiVersion: v1
kind: Pod
metadata: 
  name: pv-pod-test
spec:
    restartPolicy: OnFailure
    containers:
    - name: busybox
      image: busybox:stable
      command: ['sh','-c','cat /data/data.txt']
      volumeMounts:
      - name: pv-host-data
        mountPath: /data
    volumes:
    - name: pv-host-data
      persistentVolumeClaim:
        claimName: hostpath-pvc