apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: list-pods-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: list-pods-rb
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: default
roleRef:
    kind: Role
    name: list-pods-role
    apiGroup: rbac.authorization.k8s.io
    