kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30201
    hostPort: 30201
    listenAddress: "0.0.0.0"


#$ kind create cluster --name terraform-kubernetes-demo --config kind-config.yml
#$ kind get clusters
#kind is a tool for running local Kubernetes clusters using Docker container “nodes”.
#kind was primarily designed for testing Kubernetes itself, but may be used for local development or CI.
# kubectl cluster-info --context kind-terraform-kubernetes-demo

#$ kubectl config view --minify --flatten --context=kind-terraform-kubernetes-demo
#cmd to retrieve all the configuration 
#host address
#client-certificate-data
#client-key-data
#certificate authority data

#delete cluster
#$ kind delete cluster --name lab-terraform-kubernetes
