---
- name: Install NGINX
  hosts: all
  tasks:
  - name: Install NGINX on Debian
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"
  - name: Install NGINX on redHat
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "redhat" or
          ansible_os_family == "SUSE"

---
- name: Check status of a service and emial if its down
  hosts: localhost
  tasks:
    - command: service httpd status
      register: result
    - mail:
        to: admin@company.com
        subject: Service Alert
        body: Httpd Service is down
        when: result.stdout.find('down') != -1

---
- name: Install apache
  hosts: all
  gather_facts: True
  tasks:
    - name: install apache2 when Ubuntu
      package:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: install httpd when CentOS
      package:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"