---
- name: Print hello message
  hosts: all
  gather_facts: no
  tasks:
  - debug:
      var: ansible_facts
    
# ansible.cfg
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default , must say gather_facts: True
# gathering  = implicit
