---
- hosts: localhost
  become: yes
  ignore_errors: yes
  tasks:
    - name: install fluffy
      yum:
        name: fluffy
        state: latest
    - debug:
        msg: "ATTEMPTED FLUFFY INSTALL!"