#Use variables to retrieve the results of running commands

---
- name: Check /etc/hosts file
  hosts: all
  tasks:
  - shell: cat /etc/hosts
    register: result
  - debug:
      var: result

#- debug: var=uptime_result.stdout

# the registered variable is stored in memory 

---
- hosts: all
  gather_facts: no  
  tasks:    
    - name: stat module help to find the file info
      stat:
        path: /var/run
      register: your_variable

    # for your reference, check the outputs of these
    - debug:
       var=your_variable.stat

    # your code goes here...
    - shell: echo "{{your_variable.stat}}" > /tmp/by_ansible