#Ansible conditional 

- name: Install NGINX
  hosts: all
  tasks: 
  - name: Install NGINX on Debian
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"   and
          ansible_distribution_version == "16.04"

  - name: Install NGINX on Redhat
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "Redhat" or
          ansible_os_family == "SUSE"

---

- name: Install Softwares
  hosts: all
  vars:
      packages:
        - name: nginx
          required: True
        - name: mysql
          required: True
        - name: apache
          required: False
  tasks:
  - name: Install on Debian
    apt:
      name: nginx
      state: present
    when: item.required == True
    loop: "{{ packages }}"

---
- name: check status of a service and email if its down
  hosts: localhost
  tasks:
    - command: service httpd status
      register: result
    - mail:
        to: admin@company.com 
        subject: Service Alert
        body: Httpd Service is down
        when: result.stdout.find('down') != -1