- hosts: localhost
  tasks:
    - name: download transaction_list
      get_url:
        url: http://apps.l33t.com/transaction_list 
        dest: /home/ansible/transaction_list
    - debug: msg="File downloaded"

#configure the playbook to download http://apps.l33t.com/transcation_list to 'home/ansible/transaction_list' on 'localhost' and output the message "File downloaded" to stdout
