---
- hosts: all
  user: ansible
  become: yes
  gather_facts: no
  tasks: 
    - name: install elinks
      action: yum name=elinks state=installed
    
    - name: install httpd
      action: yum name=httpd state=installed
    
    - name: enable apache on system reboot
      service: name=httpd enabled=yes
    
    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started
    
    - name: install firewalld
      action: yum name=firewalld state=installed
    
    - name: Enable firewalld on system reboot
      service: name=firewalld enabled=yes
#add the firewall rule to allow port 80.
    - firewalld:
        service: http
        permanent: yes
        state: enabled 
    
    - name: restart service firewalld
      service:
        name: firewalld
        state: restarted
