# user_list.j2 : content file
#This is user list deployed from ansible
#-------------------------------------
#{# For Statement #}
#{% for user in users %}
#{{ loop.index }} : {{ user }}
#{% endfor %}
#
#
#------------------------------------
#this is end of user list


- name: Using jinja
  hosts: nodes
  become: yes
  vars:
    system_admin_email: admin@lab.com
    users:
      - john
      - mahdi
      - emma
      - gini
      - njr
  tasks:
    - name: Deploy motd
      template:
        dest: /etc/motd
        src: motd.j2

    - name: Deploy user list
      template:
        dest: /tmp/usr_list
        src: user_list.j2
