---
- name: Learn Magic Variables
  hosts: nodes
  tasks:
    - name: Show Inventory Host Name
      debug:
        msg: "{{ inventroy_hostname }}"
    - name: Show Group
      debug:
        msg: "{{ group_names }}"
    
    - name: Show Host Variable
      debug:
        msg: "{{ hostvars }}"
  