--- # Tags exemple
- hosts: localhost
  tasks:
    - name: Install elinks
      become: yes
      yum:
        name: elinks
        state: latest
      tags:
        - software
    
    - name: Add line to text file
      linefile:
        path: /home/ansible/tag-test.txt
        create: yes
        line: "Tag called!"
      tags:
        - files
        - config
    
    - name: copy tag file
      copy:
        src: /home/ansible/tag-test.txt
        dest: /tmp/copied.txt
      tags:
        - config

# ansible-playbook tags.yml --tags software
# run one more than one tag 
## ansible-playbook tags.yml --tags software,files
