---
  - name: Show varaibles
    hosts: all
    gather_facts: no
    tasks:
    - debug:
        msg:
          - "ansible_ssh_user {{ ansible_ssh_user }}"
          - "ansible_ssh_private_key_file {{ ansible_ssh_private_key_file }}"
          - "myvar {{ myvar }}"
          